name: Test Environment

on:
  workflow_dispatch:  # Manual trigger

jobs:
  test-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Test Environment Variables
        run: |
          if [ -n "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "✅ OPENAI_API_KEY is set"
          else
            echo "❌ OPENAI_API_KEY is not set"
          fi
        env:
          # Using a dummy value to test if secret exists
          TEST_KEY: ${{ secrets.OPENAI_API_KEY }}
